export const demos = [
  {
    path: "/gsap/Rainbow",
    name: "Rainbow Demo",
    category: "CSS Animations",
    description: "彩虹色彩动画效果展示",
    date: "5 DAYS AGO",
    isNew: true,
  },
  {
    path: "/gsap/AirPods",
    name: "AirPods Demo",
    category: "Product Showcase",
    description: "AirPods产品展示动画",
    date: "1 WEEK AGO",
    isNew: true,
  },
  {
    path: "/gsap/Baisc",
    name: "Basic Demo",
    category: "Fundamentals",
    description: "基础动画效果演示",
    date: "1 WEEK AGO",
    isNew: true,
  },
  {
    path: "/gsap/NavLink",
    name: "NavLink Demo",
    category: "Navigation",
    description: "导航链接动画效果",
    date: "2 WEEKS AGO",
    isNew: false,
  },
  {
    path: "/gsap/Parallax",
    name: "Parallax Demo",
    category: "Scroll Effects",
    description: "视差滚动效果演示",
    date: "2 WEEKS AGO",
    isNew: false,
  },
];

export const threeDemos = [
  {
    path: "/journey/ThreeDemos",
    name: "Three.js Demos",
    category: "3D Graphics",
    description: "Three.js 3D图形演示",
    date: "3 WEEKS AGO",
    isNew: false,
  },
  {
    path: "/journey/basic",
    name: "Three.js Basic",
    category: "3D Fundamentals",
    description: "Three.js基础场景",
    date: "1 WEEK AGO",
    isNew: true,
  },
  {
    path: "/journey/sea",
    name: "Ocean Scene",
    category: "Shader Effects",
    description: "海洋波浪着色器效果",
    date: "2 WEEKS AGO",
    isNew: false,
  },
  {
    path: "/journey/shader",
    name: "Shader Patterns",
    category: "GLSL Shaders",
    description: "GLSL着色器图案集合",
    date: "3 WEEKS AGO",
    isNew: false,
  },
];
